### ISSUE TITLE
scoped css 无效

### ISSUE THREAD

**Issue by hellobq** [zhongdeming428/MyMemorandum#12]
webpack打包Vue SPA，即使父组件设置了scoped，父组件还是影响了子组件的样式

**Comment by zhongdeming428** [comment]
能否上传你的代码到 github ，我也看看 @hellobq

**Comment by hellobq** [comment]
很抱歉。我之前对 scoped 理解错了，你的打包没问题。我也尝试了 vuecli2.x  3.x，作用一样的。

**Comment by zhongdeming428** [comment]
@hellobq 😄 祝你学习愉快，这个 issue 先关闭了~
